Feat/manage
2110366-2566-2/skillbridge pull request #53
Opened 2024-03-12 18:05 UTC by sarunnut1236

Added student task management page ("/studentjobs")
Added employer application management page ("/jobs/:id")
Refractor some bad smell

It is not completed, but there is a lot of dependency to others, so please approve

2024-03-12 20:01 UTC, mharnsingh approved these changes

2024-03-13 09:02 UTC, mharnsingh requested changes
pull from main before merging to avoid merge conflict

2024-03-13 09:07 UTC, sarunnut1236 commented
Request again naja

2024-03-13 09:33 UTC, northsurapee approved these changes

2024-03-13 09:59 UTC, mharnsingh approved these changes

2024-03-13 09:59 UTC, merged